package POJOS;
// Generated 9/10/2024 09:47:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer idLibros;
     private String genero;
     private Integer cantidad;
     private Boolean estado;
     private Set<Prestamos> prestamoses = new HashSet<Prestamos>(0);

    public Libros() {
    }

    public Libros(String genero, Integer cantidad, Boolean estado, Set<Prestamos> prestamoses) {
       this.genero = genero;
       this.cantidad = cantidad;
       this.estado = estado;
       this.prestamoses = prestamoses;
    }
   
    public Integer getIdLibros() {
        return this.idLibros;
    }
    
    public void setIdLibros(Integer idLibros) {
        this.idLibros = idLibros;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set<Prestamos> getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set<Prestamos> prestamoses) {
        this.prestamoses = prestamoses;
    }




}


