package POJOS;
// Generated 13/10/2024 07:11:05 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private Integer idLibros;
     private String nombre;
     private String genero;
     private Boolean estado;
     private String categoria;
     private Set<Prestamos> prestamoses = new HashSet<Prestamos>(0);

    public Libros() {
    }

    public Libros(String nombre, String genero, Boolean estado, String categoria, Set<Prestamos> prestamoses) {
       this.nombre = nombre;
       this.genero = genero;
       this.estado = estado;
       this.categoria = categoria;
       this.prestamoses = prestamoses;
    }
   
    public Integer getIdLibros() {
        return this.idLibros;
    }
    
    public void setIdLibros(Integer idLibros) {
        this.idLibros = idLibros;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set<Prestamos> getPrestamoses() {
        return this.prestamoses;
    }
    
    public void setPrestamoses(Set<Prestamos> prestamoses) {
        this.prestamoses = prestamoses;
    }




}


